# Workflow to ensure project builds and code is formatted properly before it is merged into main

name: Project Check

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check build
        run: npm run build --if-present

  format:
    name: Code Formatting Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Check code formatting
        run: npm run prettier
